### ISSUE TITLE
Add endpoints for creating and retrieving a user

### ISSUE THREAD

**Issue by Jarand95** [jrndapp/web-portal#1]
User should at least contain the following fields:
- id
- username
- email
- password
- userCreated
- userVerified
- userDeactivated
- emailVerified
- passwordChanged

POST /users
Create user and return 201 Created with a location link to the endpoint below.

GET /users/{id}
Return a user with a 200 status. (The user can be empty for now)

**Comment by Jarand95** [comment]
@Jarand95Review Issue approved?

**Comment by Jarand95Review** [comment]
@Jarand95 Issue approved!
